### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Xarthisius** [rootfs/install-glusterfs-on-fc21#1]
Hi @rootfs 
I'm using a modified version of `mymount.c` in some of my projects. I was convinced that it was written by one of my coworker but I turns out it's not true. You're the author of the original code. First of all, kudos for writing it! Secondly, would it possible for you to license this code (hopefully under something permissive like BSD-3) ?

**Comment by rootfs** [comment]
bsd 3 license added, happy coding!

**Comment by Xarthisius** [comment]
Thank you so much!
